// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

enum Protocol : uint16_t {
  Protocol_None = 0,
  Protocol_TextSend = 1,
  Protocol_LoginReq = 2,
  Protocol_LoginAck = 3,
  Protocol_CreateAccountReq = 4,
  Protocol_CreateAccountAck = 5,
  Protocol_CreateCharacterReq = 6,
  Protocol_CreateCharacterAck = 7,
  Protocol_CheckCharacterNicknameReq = 8,
  Protocol_CheckCharacterNicknameAck = 9,
  Protocol_SelectCharacterReq = 10,
  Protocol_SelectCharacterAck = 11,
  Protocol_ResultCode = 12,
  Protocol_MIN = Protocol_None,
  Protocol_MAX = Protocol_ResultCode
};

inline const Protocol (&EnumValuesProtocol())[13] {
  static const Protocol values[] = {
    Protocol_None,
    Protocol_TextSend,
    Protocol_LoginReq,
    Protocol_LoginAck,
    Protocol_CreateAccountReq,
    Protocol_CreateAccountAck,
    Protocol_CreateCharacterReq,
    Protocol_CreateCharacterAck,
    Protocol_CheckCharacterNicknameReq,
    Protocol_CheckCharacterNicknameAck,
    Protocol_SelectCharacterReq,
    Protocol_SelectCharacterAck,
    Protocol_ResultCode
  };
  return values;
}

inline const char * const *EnumNamesProtocol() {
  static const char * const names[14] = {
    "None",
    "TextSend",
    "LoginReq",
    "LoginAck",
    "CreateAccountReq",
    "CreateAccountAck",
    "CreateCharacterReq",
    "CreateCharacterAck",
    "CheckCharacterNicknameReq",
    "CheckCharacterNicknameAck",
    "SelectCharacterReq",
    "SelectCharacterAck",
    "ResultCode",
    nullptr
  };
  return names;
}

inline const char *EnumNameProtocol(Protocol e) {
  if (flatbuffers::IsOutRange(e, Protocol_None, Protocol_ResultCode)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProtocol()[index];
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
