// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

enum Protocol : uint16_t {
  Protocol_None = 0,
  Protocol_TextSend = 1,
  Protocol_Login = 2,
  Protocol_CreateAccount = 3,
  Protocol_CreateCharacter = 4,
  Protocol_CheckCharacterNickname = 5,
  Protocol_ResultCode = 6,
  Protocol_MIN = Protocol_None,
  Protocol_MAX = Protocol_ResultCode
};

inline const Protocol (&EnumValuesProtocol())[7] {
  static const Protocol values[] = {
    Protocol_None,
    Protocol_TextSend,
    Protocol_Login,
    Protocol_CreateAccount,
    Protocol_CreateCharacter,
    Protocol_CheckCharacterNickname,
    Protocol_ResultCode
  };
  return values;
}

inline const char * const *EnumNamesProtocol() {
  static const char * const names[8] = {
    "None",
    "TextSend",
    "Login",
    "CreateAccount",
    "CreateCharacter",
    "CheckCharacterNickname",
    "ResultCode",
    nullptr
  };
  return names;
}

inline const char *EnumNameProtocol(Protocol e) {
  if (flatbuffers::IsOutRange(e, Protocol_None, Protocol_ResultCode)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProtocol()[index];
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
