// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace world
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MoveStartSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static MoveStartSync GetRootAsMoveStartSync(ByteBuffer _bb) { return GetRootAsMoveStartSync(_bb, new MoveStartSync()); }
  public static MoveStartSync GetRootAsMoveStartSync(ByteBuffer _bb, MoveStartSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MoveStartSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ObjId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public Vec2? Dir { get { int o = __p.__offset(6); return o != 0 ? (Vec2?)(new Vec2()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Speed { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartMoveStartSync(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddObjId(FlatBufferBuilder builder, uint objId) { builder.AddUint(0, objId, 0); }
  public static void AddDir(FlatBufferBuilder builder, Offset<Vec2> dirOffset) { builder.AddStruct(1, dirOffset.Value, 0); }
  public static void AddSpeed(FlatBufferBuilder builder, float speed) { builder.AddFloat(2, speed, 0.0f); }
  public static Offset<world.MoveStartSync> EndMoveStartSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<world.MoveStartSync>(o);
  }
};


}
