// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace world
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MoveStopSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static MoveStopSync GetRootAsMoveStopSync(ByteBuffer _bb) { return GetRootAsMoveStopSync(_bb, new MoveStopSync()); }
  public static MoveStopSync GetRootAsMoveStopSync(ByteBuffer _bb, MoveStopSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MoveStopSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ObjId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public Vec3? Pos { get { int o = __p.__offset(6); return o != 0 ? (Vec3?)(new Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartMoveStopSync(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddObjId(FlatBufferBuilder builder, uint objId) { builder.AddUint(0, objId, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<Vec3> posOffset) { builder.AddStruct(1, posOffset.Value, 0); }
  public static Offset<world.MoveStopSync> EndMoveStopSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<world.MoveStopSync>(o);
  }
};


}
