// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace account
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SelectCharacterReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static SelectCharacterReq GetRootAsSelectCharacterReq(ByteBuffer _bb) { return GetRootAsSelectCharacterReq(_bb, new SelectCharacterReq()); }
  public static SelectCharacterReq GetRootAsSelectCharacterReq(ByteBuffer _bb, SelectCharacterReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SelectCharacterReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong CharId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<account.SelectCharacterReq> CreateSelectCharacterReq(FlatBufferBuilder builder,
      ulong char_id = 0) {
    builder.StartTable(1);
    SelectCharacterReq.AddCharId(builder, char_id);
    return SelectCharacterReq.EndSelectCharacterReq(builder);
  }

  public static void StartSelectCharacterReq(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharId(FlatBufferBuilder builder, ulong charId) { builder.AddUlong(0, charId, 0); }
  public static Offset<account.SelectCharacterReq> EndSelectCharacterReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<account.SelectCharacterReq>(o);
  }
};


}
