// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum ResultCode : ushort
{
  None = 0,
  CreateSuccess = 1,
  CreateFailure = 2,
  AleadyExist = 3,
  NotExist = 4,
  LoginSuccess = 5,
  LoginFailure = 6,
  EnterGameSuccess = 7,
  EnterGameFailure = 8,
};

