// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Protocol : ushort
{
  None = 0,
  TextSend = 1,
  LoginReq = 2,
  LoginAck = 3,
  CreateAccountReq = 4,
  CreateAccountAck = 5,
  CreateCharacterReq = 6,
  CreateCharacterAck = 7,
  CheckCharacterNicknameReq = 8,
  CheckCharacterNicknameAck = 9,
  SelectCharacterReq = 10,
  SelectCharacterAck = 11,
  EnterFieldSync = 12,
  MoveStartSync = 13,
  MoveStopSync = 14,
  ResultCode = 15,
};

