// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace account
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LoginReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static LoginReq GetRootAsLoginReq(ByteBuffer _bb) { return GetRootAsLoginReq(_bb, new LoginReq()); }
  public static LoginReq GetRootAsLoginReq(ByteBuffer _bb, LoginReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Pw { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPwBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPwBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPwArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<account.LoginReq> CreateLoginReq(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      StringOffset pwOffset = default(StringOffset)) {
    builder.StartTable(2);
    LoginReq.AddPw(builder, pwOffset);
    LoginReq.AddId(builder, idOffset);
    return LoginReq.EndLoginReq(builder);
  }

  public static void StartLoginReq(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddPw(FlatBufferBuilder builder, StringOffset pwOffset) { builder.AddOffset(1, pwOffset.Value, 0); }
  public static Offset<account.LoginReq> EndLoginReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<account.LoginReq>(o);
  }
}


}
